services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: production
    command: pnpm run start:dev reservations --host 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: production
    command: pnpm run start:dev auth
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    command: mongod --bind_ip_all
    ports:
      - 27017:27017
