apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
    app.kubernetes.io/managed-by: Helm
  name: notifications
  annotations:
    meta.helm.sh/release-name: cabr
    meta.helm.sh/release-namespace: default
spec:
  ports:
    - name: 'tcp'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: notifications
  type: ClusterIP
