apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notifications
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/cabr-399120/notifications/production
        name: production
        resources: {}
status: {}
